package model;

import java.util.ArrayList;

public class ShayanMap {
    public static void myTiles() {

        Maps map = new Maps(25, 80);

        Feature Jungle = new Feature("Jungle", 2, 1, 0.25, 0, 1);
        Feature Forest = new Feature("Forest", 2, 1, 0.25, 0, 1);
        Feature Marsh = new Feature("Marsh", 2, -1, -0.33, 0, 0);
        Feature Oasis = new Feature("Oasis", 1, 3, -0.33, 1, 0);
        Feature Ice = new Feature("Ice", 0, 0, 0, 0, 0);
        Feature FloodPlain = new Feature("FloodPlain", 1, 2, -0.33, 0, 0);


        Terrain Desert = new Terrain("Desert", "yellow", 1, 0, -0.33, 0, 0, true);
        Terrain GrassLand = new Terrain("Grassland", "green", 1, 2, -0.33, 0, 0, true);
        Terrain Hill = new Terrain("Hill", "purple", 2, 0, 0.25, 0, 2, true);
        Terrain Mountain = new Terrain("Mountain", "brightBlack", 0, 0, 0, 0, 0, false);
        Terrain Ocean = new Terrain("Ocean", "brightBlue", 0, 0, 0, 0, 0, false);
        Terrain Plain = new Terrain("Plain", "red", 1, 1, -0.33, 0, 1, true);
        Terrain Snow = new Terrain("Snow", "white", 1, 0, -0.33, 0, 0, true);
        //13th row
        // between asia and america
        Tile tile = new Tile(12, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 8, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // america
        tile = new Tile(12, 9, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 10, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 11, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 12, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 13, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 14, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 16, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 17, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 20, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 21, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 22, null, Mountain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 23, null, Mountain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        //between europe and america
        tile = new Tile(12, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 39, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // england
        tile = new Tile(12, 33, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 34, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 35, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between england and france
        tile = new Tile(12, 36, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // 33 europe and asia
        tile = new Tile(12, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 38, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 40, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 41, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 42, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 43, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 44, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 45, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 46, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 47, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 48, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 49, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 50, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 51, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 52, null, Mountain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 53, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 54, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 55, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 56, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 57, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 58, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 59, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 60, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 61, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 62, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 63, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 64, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 65, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 66, null, Plain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 67, null, Plain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 68, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 69, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between china and japan
        tile = new Tile(12, 70, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 71, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 72, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 73, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // japan
        tile = new Tile(12, 74, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 75, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between Japan and america
        tile = new Tile(12, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 77, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(12, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(12, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        //14th row between america and asia

        tile = new Tile(13, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        //west america
        tile = new Tile(13, 8, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 9, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 10, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 11, null, GrassLand, 0, false, null, null, Marsh);
        map.setTileBoard(tile);
        tile = new Tile(13, 12, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 13, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // a lake
        tile = new Tile(13, 14, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // east America
        tile = new Tile(13, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 16, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 17, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 20, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 21, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 22, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 23, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between america and europe
        tile = new Tile(13, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 33, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 34, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 35, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe to asia
        tile = new Tile(13, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 38, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 40, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 41, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 42, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 43, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 44, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 45, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 46, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 47, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 48, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 49, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 50, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 51, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 52, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 53, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 54, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 55, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 56, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 57, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 58, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 59, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 60, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 61, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 62, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 63, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 64, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 65, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 66, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 67, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 68, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 69, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 70, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(13, 71, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(13, 72, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 73, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 74, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(13, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        //15th row

        // between asia and america
        tile = new Tile(14, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 8, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        //west america
        tile = new Tile(14, 9, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 10, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 11, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 12, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 13, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 14, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        //a lake
        tile = new Tile(14, 16, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // east america
        tile = new Tile(14, 17, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 20, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 21, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 22, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // america to europe
        tile = new Tile(14, 23, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        //europe and asia 38
        tile = new Tile(14, 33, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 34, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 35, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 38, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 40, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 41, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 42, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 43, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 44, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 45, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 46, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 47, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 48, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 49, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 50, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 51, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 52, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 53, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 54, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 55, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 56, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 57, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 58, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 59, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 60, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 61, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 62, null, Desert, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 63, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 64, null, Plain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 65, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 66, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 67, null, Plain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 68, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 69, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 70, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(14, 71, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 72, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 73, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 74, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(14, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(14, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        // 16th row
        //between asia and america
        tile = new Tile(15, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // west america
        tile = new Tile(15, 8, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 9, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 10, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 11, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 12, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 13, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 14, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // a lake
        tile = new Tile(15, 16, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 17, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        //east america
        tile = new Tile(15, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 20, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 21, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 22, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between america and europe
        tile = new Tile(15, 23, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(15, 33, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 34, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 35, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 38, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 40, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 41, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 42, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 43, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 44, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 45, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 46, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 47, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 48, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        // Caspian sea
        tile = new Tile(15, 49, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // asia
        tile = new Tile(15, 50, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 51, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 52, null, Desert, 0, false, null, null, Oasis);
        map.setTileBoard(tile);
        tile = new Tile(15, 53, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 54, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 55, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 56, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 57, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 58, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 59, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 60, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 61, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 62, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 63, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 64, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 65, null, Desert, 0, false, null, null, Oasis);
        map.setTileBoard(tile);
        tile = new Tile(15, 66, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 67, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 68, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(15, 69, null, Mountain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(15, 70, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 71, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // japan
        tile = new Tile(15, 72, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 73, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        // between asia and europe
        tile = new Tile(15, 74, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(15, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        // 17th row
        // between asia and america
        tile = new Tile(16, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 8, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        //west america
        tile = new Tile(16, 9, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 10, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 11, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 12, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 13, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 14, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // a lake
        tile = new Tile(16, 16, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // east america
        tile = new Tile(16, 17, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 20, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 21, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between america and europe
        tile = new Tile(16, 22, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 23, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 33, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(16, 34, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 35, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 38, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 39, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 40, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 41, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 42, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 43, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 44, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // Black Sea
        tile = new Tile(16, 45, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 46, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 47, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // island
        tile = new Tile(16, 48, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        // caspian sea
        tile = new Tile(16, 49, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 50, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // asia
        tile = new Tile(16, 51, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 52, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 53, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 54, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 55, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 56, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 57, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 58, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 59, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 60, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 61, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 62, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 63, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 64, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 65, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 66, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 67, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 68, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(16, 69, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(16, 70, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 71, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // japan
        tile = new Tile(16, 72, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 73, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        // between asia and america
        tile = new Tile(16, 74, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(16, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        // 18th row

        tile = new Tile(17, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // america
        tile = new Tile(17, 8, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 9, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 10, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 11, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 12, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 13, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 14, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 16, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 17, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 19, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between america and europe
        tile = new Tile(17, 20, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 21, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 22, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 23, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 32, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 33, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(17, 34, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 35, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 37, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 38, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 40, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 41, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 42, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 43, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 44, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // Black Sea
        tile = new Tile(17, 45, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 46, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // island
        tile = new Tile(17, 47, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 48, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        // caspian sea
        tile = new Tile(17, 49, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // asia
        tile = new Tile(17, 50, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 51, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 52, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 53, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 54, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 55, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 56, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 57, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 58, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 59, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 60, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 61, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 62, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 63, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 64, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 65, null, Plain, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 66, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 67, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 68, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(17, 69, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 70, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // japan
        tile = new Tile(17, 71, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(17, 72, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between asia and america
        tile = new Tile(17, 73, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 74, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(17, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);

        // 19th row
        // between asia and america
        tile = new Tile(18, 0, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 1, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 2, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 3, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 4, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 5, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 6, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 7, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 8, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // america
        tile = new Tile(18, 9, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 10, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 11, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 12, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 13, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 14, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 15, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 16, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 17, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 18, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // between america and europe
        tile = new Tile(18, 19, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 20, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 21, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 22, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 23, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 24, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 25, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 26, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 27, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 28, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 29, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 30, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 31, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(18, 32, null, Hill, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 33, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 34, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 35, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 36, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // sea
        tile = new Tile(18, 37, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 38, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(18, 39, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 40, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // sea
        tile = new Tile(18, 41, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // europe
        tile = new Tile(18, 42, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 43, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        // sea
        tile = new Tile(18, 44, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // asia
        tile = new Tile(18, 45, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 46, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 47, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 48, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 49, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 50, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 51, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 52, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 53, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 54, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 55, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 56, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 57, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 58, null, Desert, 0, false, null, null, Oasis);
        map.setTileBoard(tile);
        tile = new Tile(18, 59, null, Desert, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 60, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 61, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 62, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 63, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 64, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 65, null, Mountain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 66, null, Plain, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 67, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 68, null, GrassLand, 0, false, null, null, null);
        map.setTileBoard(tile);
        // east asian sea
        tile = new Tile(18, 69, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 70, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        // japan
        tile = new Tile(18, 71, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 72, null, GrassLand, 0, false, null, null, Forest);
        map.setTileBoard(tile);
        tile = new Tile(18, 73, null, Hill, 0, false, null, null, null);
        map.setTileBoard(tile);
        // between america and asia
        tile = new Tile(18, 74, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 75, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 76, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 77, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 78, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);
        tile = new Tile(18, 79, null, Ocean, 0, false, null, null, null);
        map.setTileBoard(tile);



    }
}
