package view.enums;

import javafx.scene.image.Image;

public class Images {
    public Image normalMenuButton;
    public Image selectedMenuButton;
    public Image submitMenuButton;
    public Image mainMenuButtonBackGround;
    public Image desertCell;
    public Image hillCell;
    public Image plainCell;
    public Image snowCell;
    public Image tundraCell;
    public Image grasslandCell;
    public Image jungleCell;
    public Image oceanCell;
    public Image mountainCell;
    public Image mountainCell2;
    public Image forestCell;
    public Image marshCell;
    public Image iceCell;
    public Image floodPlainCell;
    public Image oasisCell;
    public Image banana;
    public Image coal;
    public Image color;
    public Image cotton;
    public Image cow;
    public Image deer;
    public Image fumigation;
    public Image fur;
    public Image gemStone;
    public Image gold;
    public Image horse;
    public Image iron;
    public Image ivory;
    public Image marble;
    public Image sheep;
    public Image silk;
    public Image silver;
    public Image sugar;
    public Image wheat;
    public Image floodPlain;
    public Image forest;
    public Image jungle;
    public Image ice;
    public Image marsh;
    public Image oasis;
    public Image avatar1;
    public Image avatar2;
    public Image avatar3;
    public Image avatar4;
    public Image avatar5;
    public Image avatar6;
    public Image avatar7;
    public Image avatar8;
    public Image avatar9;
    public Image avatar10;

    public Images(){
        normalMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Down.png")));
        selectedMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Selected.png")));
        submitMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Normal.png")));
        //mainMenuButtonBackGround = new Image(String.valueOf(getClass().getResource("/Media/buttons/Menu-buttons-pic.png")));
        desertCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/DesertCell.png")));
        hillCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/HillCell.png")));
        plainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/PlainCell.png")));
        snowCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/snowCell.png")));
        tundraCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/TundraCell.png")));
        grasslandCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/GrasslandCell.png")));
        jungleCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/JungleCell.png")));
        oceanCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/OceanCell.png")));
        mountainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/MountainCell.png")));
        mountainCell2 = new Image(String.valueOf(getClass().getResource("/Media/tiles/MountainCell2.png")));
        forestCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/forestCell.png")));
        iceCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/iceCell.png")));
        marshCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/PlainCell2.png")));
        floodPlainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/floodPlainCell.png")));
        oasisCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/oasisCell.png")));
        banana = new Image(String.valueOf(getClass().getResource("/Media/resource/banana.png")));
        coal = new Image(String.valueOf(getClass().getResource("/Media/resource/coal.png")));
        color = new Image(String.valueOf(getClass().getResource("/Media/resource/color.png")));
        cotton = new Image(String.valueOf(getClass().getResource("/Media/resource/cotton.png")));
        cow = new Image(String.valueOf(getClass().getResource("/Media/resource/cow.png")));
        deer = new Image(String.valueOf(getClass().getResource("/Media/resource/deer.png")));
        fumigation = new Image(String.valueOf(getClass().getResource("/Media/resource/fumigation.png")));
        fur = new Image(String.valueOf(getClass().getResource("/Media/resource/fur.png")));
        gemStone = new Image(String.valueOf(getClass().getResource("/Media/resource/gemStone.png")));
        gold = new Image(String.valueOf(getClass().getResource("/Media/resource/gold.png")));
        horse = new Image(String.valueOf(getClass().getResource("/Media/resource/horse.png")));
        iron = new Image(String.valueOf(getClass().getResource("/Media/resource/iron.png")));
        ivory = new Image(String.valueOf(getClass().getResource("/Media/resource/ivory.png")));
        marble = new Image(String.valueOf(getClass().getResource("/Media/resource/marble.png")));
        sheep = new Image(String.valueOf(getClass().getResource("/Media/resource/sheep.png")));
        silk = new Image(String.valueOf(getClass().getResource("/Media/resource/silk.png")));
        silver = new Image(String.valueOf(getClass().getResource("/Media/resource/silver.png")));
        sugar = new Image(String.valueOf(getClass().getResource("/Media/resource/sugar.png")));
        wheat = new Image(String.valueOf(getClass().getResource("/Media/resource/wheat.png")));
        floodPlain = new Image(String.valueOf(getClass().getResource("/Media/tiles/floodPlains.png")));
        forest = new Image(String.valueOf(getClass().getResource("/Media/tiles/forest.png")));
        jungle = new Image(String.valueOf(getClass().getResource("/Media/tiles/jungle.png")));
        ice = new Image(String.valueOf(getClass().getResource("/Media/tiles/ice.png")));
        marsh = new Image(String.valueOf(getClass().getResource("/Media/tiles/marsh.png")));
        oasis = new Image(String.valueOf(getClass().getResource("/Media/tiles/oasis.png")));
        avatar1 = new Image(getClass().getResource("/Media/avatars/avatar1.png").toExternalForm());
        avatar2 = new Image(getClass().getResource("/Media/avatars/avatar2.png").toExternalForm());
        avatar3 = new Image(getClass().getResource("/Media/avatars/avatar3.png").toExternalForm());
        avatar4 = new Image(getClass().getResource("/Media/avatars/avatar4.png").toExternalForm());
        avatar5 = new Image(getClass().getResource("/Media/avatars/avatar5.png").toExternalForm());
        avatar6 = new Image(getClass().getResource("/Media/avatars/avatar6.png").toExternalForm());
        avatar7 = new Image(getClass().getResource("/Media/avatars/avatar7.png").toExternalForm());
        avatar8 = new Image(getClass().getResource("/Media/avatars/avatar8.png").toExternalForm());
        avatar9 = new Image(getClass().getResource("/Media/avatars/avatar9.png").toExternalForm());
        avatar10 = new Image(getClass().getResource("/Media/avatars/avatar10.png").toExternalForm());

    }
}
