package view.enums;

import javafx.scene.image.Image;

public class Images {
    public Image normalMenuButton;
    public Image selectedMenuButton;
    public Image submitMenuButton;
    public Image mainMenuButtonBackGround;
    public Image desertCell;
    public Image hillCell;
    public Image plainCell;
    public Image snowCell;
    public Image tundraCell;
    public Image grasslandCell;
    public Image jungleCell;
    public Image oceanCell;
    public Image mountainCell;
    public Image mountainCell2;
    public Image forestCell;
    public Image marshCell;
    public Image iceCell;
    public Image floodPlainCell;
    public Image oasisCell;
    public Image banana;
    public Image coal;
    public Image color;
    public Image cotton;
    public Image cow;
    public Image deer;
    public Image fumigation;
    public Image fur;
    public Image gemStone;
    public Image goldResource;
    public Image horse;
    public Image iron;
    public Image ivory;
    public Image marble;
    public Image sheep;
    public Image silk;
    public Image silver;
    public Image sugar;
    public Image wheat;
    public Image gold;
    public Image science;
    public Image food;
    public Image production;
    public Image happiness;
    public Image unhappiness;
    public Image chariotArcher;
    public Image scout;
    public Image settler;
    public Image spearman;
    public Image warrior;
    public Image worker;
    public Image catapult;
    public Image horseman;
    public Image swordMan;
    public Image crossbowman;
    public Image knight;
    public Image longSwordsman;
    public Image pikeMan;
    public Image trebuchet;
    public Image canon;
    public Image cavalry;
    public Image lancer;
    public Image musketMan;
    public Image rifleMan;
    public Image antiTankGun;
    public Image artillery;
    public Image infantry;
    public Image panzer;
    public Image tank;
    public Image city;
    public Image avatar1;
    public Image avatar2;
    public Image avatar3;
    public Image avatar4;
    public Image avatar5;
    public Image avatar6;
    public Image avatar7;
    public Image avatar8;
    public Image avatar9;
    public Image avatar10;

    public Images(){
        normalMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Down.png")));
        selectedMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Selected.png")));
        submitMenuButton = new Image(String.valueOf(getClass().getResource("/Media/buttons/Button_Normal.png")));
        //mainMenuButtonBackGround = new Image(String.valueOf(getClass().getResource("/Media/buttons/Menu-buttons-pic.png")));
        desertCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/DesertCell.png")));
        hillCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/HillCell.png")));
        plainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/PlainCell.png")));
        snowCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/snowCell.png")));
        tundraCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/TundraCell.png")));
        grasslandCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/GrasslandCell.png")));
        jungleCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/JungleCell.png")));
        oceanCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/OceanCell.png")));
        mountainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/MountainCell.png")));
        mountainCell2 = new Image(String.valueOf(getClass().getResource("/Media/tiles/MountainCell2.png")));
        forestCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/forestCell.png")));
        iceCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/iceCell.png")));
        marshCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/PlainCell2.png")));
        floodPlainCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/floodPlainCell.png")));
        oasisCell = new Image(String.valueOf(getClass().getResource("/Media/tiles/oasisCell.png")));
        banana = new Image(String.valueOf(getClass().getResource("/Media/resource/banana.png")));
        coal = new Image(String.valueOf(getClass().getResource("/Media/resource/coal.png")));
        color = new Image(String.valueOf(getClass().getResource("/Media/resource/color.png")));
        cotton = new Image(String.valueOf(getClass().getResource("/Media/resource/cotton.png")));
        cow = new Image(String.valueOf(getClass().getResource("/Media/resource/cow.png")));
        deer = new Image(String.valueOf(getClass().getResource("/Media/resource/deer.png")));
        fumigation = new Image(String.valueOf(getClass().getResource("/Media/resource/fumigation.png")));
        fur = new Image(String.valueOf(getClass().getResource("/Media/resource/fur.png")));
        gemStone = new Image(String.valueOf(getClass().getResource("/Media/resource/gemStone.png")));
        goldResource = new Image(String.valueOf(getClass().getResource("/Media/resource/gold.png")));
        horse = new Image(String.valueOf(getClass().getResource("/Media/resource/horse.png")));
        iron = new Image(String.valueOf(getClass().getResource("/Media/resource/iron.png")));
        ivory = new Image(String.valueOf(getClass().getResource("/Media/resource/ivory.png")));
        marble = new Image(String.valueOf(getClass().getResource("/Media/resource/marble.png")));
        sheep = new Image(String.valueOf(getClass().getResource("/Media/resource/sheep.png")));
        silk = new Image(String.valueOf(getClass().getResource("/Media/resource/silk.png")));
        silver = new Image(String.valueOf(getClass().getResource("/Media/resource/silver.png")));
        sugar = new Image(String.valueOf(getClass().getResource("/Media/resource/sugar.png")));
        wheat = new Image(String.valueOf(getClass().getResource("/Media/resource/wheat.png")));
        gold = new Image(String.valueOf(getClass().getResource("/Media/icons/gold.png")));
        science = new Image(String.valueOf(getClass().getResource("/Media/icons/science.png")));
        food = new Image(String.valueOf(getClass().getResource("/Media/icons/food.png")));
        production = new Image(String.valueOf(getClass().getResource("/Media/icons/production.png")));
        happiness = new Image(String.valueOf(getClass().getResource("/Media/icons/happiness.png")));
        unhappiness = new Image(String.valueOf(getClass().getResource("/Media/icons/unhappiness.png")));
        chariotArcher = new Image(String.valueOf(getClass().getResource("/Media/Units/Chariot Archer.png")));
        scout = new Image(String.valueOf(getClass().getResource("/Media/Units/Scout.png")));
        settler = new Image(String.valueOf(getClass().getResource("/Media/Units/Settler.png")));
        spearman = new Image(String.valueOf(getClass().getResource("/Media/Units/Spearman.png")));
        warrior = new Image(String.valueOf(getClass().getResource("/Media/Units/Warrior.png")));
        worker = new Image(String.valueOf(getClass().getResource("/Media/Units/Worker.png")));
        catapult = new Image(String.valueOf(getClass().getResource("/Media/Units/Catapult.png")));
        horseman = new Image(String.valueOf(getClass().getResource("/Media/Units/Horseman.png")));
        swordMan = new Image(String.valueOf(getClass().getResource("/Media/Units/Swordsman.png")));
        crossbowman = new Image(String.valueOf(getClass().getResource("/Media/Units/Crossbowman.png")));
        knight = new Image(String.valueOf(getClass().getResource("/Media/Units/Knight.png")));
        longSwordsman = new Image(String.valueOf(getClass().getResource("/Media/Units/Longswordsman.png")));
        pikeMan = new Image(String.valueOf(getClass().getResource("/Media/Units/Pikeman.png")));
        trebuchet = new Image(String.valueOf(getClass().getResource("/Media/Units/Trebuchet.png")));
        canon = new Image(String.valueOf(getClass().getResource("/Media/Units/Cannon.png")));
        cavalry = new Image(String.valueOf(getClass().getResource("/Media/Units/Cavalry.png")));
        lancer = new Image(String.valueOf(getClass().getResource("/Media/Units/Lancer.png")));
        musketMan = new Image(String.valueOf(getClass().getResource("/Media/Units/Musketman.png")));
        rifleMan = new Image(String.valueOf(getClass().getResource("/Media/Units/Rifleman.png")));
        antiTankGun = new Image(String.valueOf(getClass().getResource("/Media/Units/Anti-Tank Gun.png")));
        artillery = new Image(String.valueOf(getClass().getResource("/Media/Units/Artillery.png")));
        infantry = new Image(String.valueOf(getClass().getResource("/Media/Units/Infantry.png")));
        panzer = new Image(String.valueOf(getClass().getResource("/Media/Units/Panzer.png")));
        tank = new Image(String.valueOf(getClass().getResource("/Media/Units/Tank.png")));
        city = new Image(String.valueOf(getClass().getResource("/Media/city/City.png")));
        avatar1 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar1.png")));
        avatar2 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar2.png")));
        avatar3 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar3.png")));
        avatar4 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar4.png")));
        avatar5 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar5.png")));
        avatar6 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar6.png")));
        avatar7 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar7.png")));
        avatar8 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar8.png")));
        avatar9 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar9.png")));
        avatar10 = new Image(String.valueOf(getClass().getResource("/Media/avatars/avatar10.png")));
    }
}
